=== stipeperan/ddm-project2/dataset/mongodb-schemas (old)/gyms_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Gym",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "_id",
    "name",
    "location",
    "leader_id"
  ],
  "properties": {
    "_id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "leader_id": {
      "type": "string"
    }
  }
}

=== stipeperan/ddm-project2/dataset/json/gyms.json
[
  {
    "_id": "g0",
    "name": "Gym_0",
    "location": "City_0",
    "leader_id": "t5849"
  },
  {
    "_id": "g1",
    "name": "Gym_1",
    "location": "City_1",
    "leader_id": "t10261"
  },
  {
    "_id": "g2",
    "name": "Gym_2",
    "location": "City_2",
    "leader_id": "t220"
  },
  {
    "_id": "g3",
    "name": "Gym_3",
    "location": "City_3",
    "leader_id": "t8135"
  },
  {
    "_id": "g4",
    "name": "Gym_4",
    "location": "City_4",
    "leader_id": "t2324"
  },
  {
    "_id": "g5",
    "name": "Gym_5",
    "location": "City_5",
    "leader_id": "t7579"
  },
  {
    "_id": "g6",
    "name": "Gym_6",
    "location": "City_6",
    "leader_id": "t6487"
  },
  {
    "_id": "g7",
    "name": "Gym_7",
    "location": "City_7",
    "leader_id": "t5799"
  },
  {
    "_id": "g8",
    "name": "Gym_8",
    "location": "City_8",
    "leader_id": "t4450"
  },
  {
    "_id": "g9",
    "name": "Gym_9",
    "location": "City_9",
    "leader_id": "t9114"
  },
  {
    "_id": "g10",
    "name": "Gym_10",
    "location": "City_10",
    "leader_id": "t10300"
  },
  {
    "_id": "g11",
    "name": "Gym_11",
    "location": "City_11",
    "leader_id": "t8574"
  },
  {
    "_id": "g12",
    "name": "Gym_12",
    "location": "City_12",
    "leader_id": "t7785"
  },
  {
    "_id": "g13",
    "name": "Gym_13",
    "location": "City_13",
    "leader_id": "t1058"
  },
  {
    "_id": "g14",
    "name": "Gym_14",
    "location": "City_14",
    "leader_id": "t9649"
  },
  {
    "_id": "g15",
    "name": "Gym_15",
    "location": "City_15",
    "leader_id": "t3817"
  },
  {
    "_id": "g16",
    "name": "Gym_16",
    "location": "City_16",
    "leader_id": "t3671"
  },
  {
    "_id": "g17",
    "name": "Gym_17",
    "location": "City_17",
    "leader_id": "t11668"
  },
  {
    "_id": "g18",
    "name": "Gym_18",
    "location": "City_18",
    "leader_id": "t2126"
  },
  {
    "_id": "g19",
    "name": "Gym_19",
    "location": "City_19",
    "leader_id": "t7404"
  },
  {
    "_id": "g20",
    "name": "Gym_20",
    "location": "City_20",
    "leader_id": "t6499"
  },
  {
    "_id": "g21",
    "name": "Gym_21",
    "location": "City_21",
    "leader_id": "t385"
  },
  {
    "_id": "g22",
    "name": "Gym_22",
    "location": "City_22",
    "leader_id": "t10761"
  },
  {
    "_id": "g23",
    "name": "Gym_23",
    "location": "City_23",
    "leader_id": "t10229"
  },
  {
    "_id": "g24",
    "name": "Gym_24",
    "location": "City_24",
    "leader_id": "t9391"
  },
  {
    "_id": "g25",
    "name": "Gym_25",
    "location": "City_25",
    "leader_id": "t9670"
  },
  {
    "_id": "g26",
    "name": "Gym_26",
    "location": "City_26",
    "leader_id": "t2788"
  },
  {
    "_id": "g27",
    "name": "Gym_27",
    "location": "City_27",
    "leader_id": "t8623"
  },
  {
    "_id": "g28",
    "name": "Gym_28",
    "location": "City_28",
    "leader_id": "t6428"
  },
  {
    "_id": "g29",
    "name": "Gym_29",
    "location": "City_29",
    "leader_id": "t7455"
  },
  {
    "_id": "g30",
    "name": "Gym_30",
    "location": "City_30",
    "leader_id": "t6162"
  },
  {
    "_id": "g31",
    "name": "Gym_31",
    "location": "City_31",
    "leader_id": "t4290"
  },
  {
    "_id": "g32",
    "name": "Gym_32",
    "location": "City_32",
    "leader_id": "t730"
  },
  {
    "_id": "g33",
    "name": "Gym_33",
    "location": "City_33",
    "leader_id": "t2396"
  },
  {
    "_id": "g34",
    "name": "Gym_34",
    "location": "City_34",
    "leader_id": "t9167"
  },
  {
    "_id": "g35",
    "name": "Gym_35",
    "location": "City_35",
    "leader_id": "t510"
  },
  {
    "_id": "g36",
    "name": "Gym_36",
    "location": "City_36",
    "leader_id": "t7891"
  },
  {
    "_id": "g37",
    "name": "Gym_37",
    "location": "City_37",
    "leader_id": "t7361"
  },
  {
    "_id": "g38",
    "name": "Gym_38",
    "location": "City_38",
    "leader_id": "t11601"
  },
  {
    "_id": "g39",
    "name": "Gym_39",
    "location": "City_39",
    "leader_id": "t4938"
  },
  {
    "_id": "g40",
    "name": "Gym_40",
    "location": "City_40",
    "leader_id": "t8763"
  },
  {
    "_id": "g41",
    "name": "Gym_41",
    "location": "City_41",
    "leader_id": "t2245"
  },
  {
    "_id": "g42",
    "name": "Gym_42",
    "location": "City_42",
    "leader_id": "t5392"
  },
  {
    "_id": "g43",
    "name": "Gym_43",
    "location": "City_43",
    "leader_id": "t7906"
  },
  {
    "_id": "g44",
    "name": "Gym_44",
    "location": "City_44",
    "leader_id": "t11131"
  },
  {
    "_id": "g45",
    "name": "Gym_45",
    "location": "City_45",
    "leader_id": "t7866"
  },
  {
    "_id": "g46",
    "name": "Gym_46",
    "location": "City_46",
    "leader_id": "t6958"
  },
  {
    "_id": "g47",
    "name": "Gym_47",
    "location": "City_47",
    "leader_id": "t2583"
  },
  {
    "_id": "g48",
    "name": "Gym_48",
    "location": "City_48",
    "leader_id": "t10205"
  },
  {
    "_id": "g49",
    "name": "Gym_49",
    "location": "City_49",
    "leader_id": "t8606"
  },
  {
    "_id": "g50",
    "name": "Gym_50",
    "location": "City_50",
    "leader_id": "t90"
  },
  {
    "_id": "g51",
    "name": "Gym_51",
    "location": "City_51",
    "leader_id": "t104"
  },
  {
    "_id": "g52",
    "name": "Gym_52",
    "location": "City_52",
    "leader_id": "t2922"
  },
  {
    "_id": "g53",
    "name": "Gym_53",
    "location": "City_53",
    "leader_id": "t10440"
  },
  {
    "_id": "g54",
    "name": "Gym_54",
    "location": "City_54",
    "leader_id": "t1882"
  },
  {
    "_id": "g55",
    "name": "Gym_55",
    "location": "City_55",
    "leader_id": "t6029"
  },
  {
    "_id": "g56",
    "name": "Gym_56",
    "location": "City_56",
    "leader_id": "t6500"
  },
  {
    "_id": "g57",
    "name": "Gym_57",
    "location": "City_57",
    "leader_id": "t4735"
  },
  {
    "_id": "g58",
    "name": "Gym_58",
    "location": "City_58",
    "leader_id": "t8042"
  },
  {
    "_id": "g59",
    "name": "Gym_59",
    "location": "City_59",
    "leader_id": "t986"
  },
  {
    "_id": "g60",
    "name": "Gym_60",
    "location": "City_60",
    "leader_id": "t849"
  },
  {
    "_id": "g61",
    "name": "Gym_61",
    "location": "City_61",
    "leader_id": "t8844"
  },
  {
    "_id": "g62",
    "name": "Gym_62",
    "location": "City_62",
    "leader_id": "t10762"
  },
  {
    "_id": "g63",
    "name": "Gym_63",
    "location": "City_63",
    "leader_id": "t11408"
  },
  {
    "_id": "g64",
    "name": "Gym_64",
    "location": "City_64",
    "leader_id": "t8409"
  },
  {
    "_id": "g65",
    "name": "Gym_65",
    "location": "City_65",
    "leader_id": "t5758"
  },
  {
    "_id": "g66",
    "name": "Gym_66",
    "location": "City_66",
    "leader_id": "t8"
  },
  {
    "_id": "g67",
    "name": "Gym_67",
    "location": "City_67",
    "leader_id": "t7873"
  }
]
